version: '3.8'
services:
  client:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/plagshield
    depends_on:
      - mongo
      - plagiarism-checker  # Ensure server waits for Python service

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  plagiarism-checker:
    build:
      context: .
      dockerfile: plagiarism-checker/Dockerfile  # Path to the Python Dockerfile
    volumes:
      - ./plagiarism-checker:/app  # Mount the plagiarism-checker directory
    expose:
      - "5001"  # Exposing port if needed
    environment:
      - MODEL_PATH=/app/models  # Path to model files
    depends_on:
      - mongo

volumes:
  mongo-data:
